#!/usr/bin/python3
"""
    Class definition of a City
"""
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from model_state import Base


class City(Base):
    """
        class City links to the MySQL table cities

        ATTRIBUTS:
        ============
            id : autogenerated unique id, not null
                Primary Key
            name : string max 128char, not null
            state_id : integer, not null
                        foreign key to states.id

    """
    __tablename__ = "cities"

    id = Column(
        Integer,
        autoincrement=True,
        unique=True,
        nullable=False,
        primary_key=True
    )
    name = Column(
        String(128),
        nullable=False
    )
    state_id = Column(
        Integer,
        ForeignKey('states.id'),
        nullable=False
    )
